title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme : mmistakes/minimal-mistakes
url:"https://github.com/scym12/studycsharp.github.io"
baseurl: ""
